openapi: 3.1.0
info:
  description: API Documentation for underground-city
  title: OpenAPI specification for the underground city application.
  version: '1.0.0'
components:
  schemas:
    Attribute:
      $ref: schemas/attribute.yml#/components/schemas/Attribute
    Product:
      $ref: schemas/product.yml#/components/schemas/Product
    Category:
      $ref: schemas/category.yml#/components/schemas/Category
    Supermarket:
      $ref: schemas/supermarket.yml#/components/schemas/Supermarket
paths:
  /attributes:
    $ref: paths/attributes.yml
  /products:
    $ref: paths/products.yml
  /supermarkets:
    $ref: paths/supermarkets.yml

responses:
  200:
    description: Successfully retrieved data.
    content:
      application/json:
        schema:
          type: object
          properties:
            Attribute:
              $ref: schemas/attribute.yml
            Product:
              $ref: schemas/product.yml
            Category:
              $ref: schemas/category.yml
            Supermarket:
              $ref: schemas/supermarket.yml