openapi: 3.0.3
info:
  description: API Documentation for underground-city
  title: OpenAPI specification for the underground city application.
  version: '1.0.0'
components:
  schemas:
    Attribute:
      $ref: './schemas/attribute.yaml#/components/schemas/Attribute'
    Product:
      $ref: './schemas/product.yaml#/components/schemas/Product'
    Category:
      $ref: './schemas/category.yaml#/components/schemas/Category'
    Supermarket:
      $ref: './schemas/supermarket.yaml#/components/schemas/Supermarket'
paths:
  /attributes:
    $ref: './paths/attributes.yaml#/paths/~1attributes'
  /products:
    $ref: './paths/products.yaml#/paths/~1products'
  /supermarkets:
    $ref: './paths/supermarkets.yaml#/paths/~1supermarkets'
