openapi: 3.1.0
components:
  schemas:
    Category:
      type: object
      properties:
        category_uuid:
          type: string
          format: uuid
          description: The UUID of the category
        category_name:
          type: string
          description: The name of the category