name: deploy-release

on:
  push:
    branches:
      - main

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r app/requirements.txt
      
      - name: Package Lambda Function
        run: |
          cd app
          zip -r ../lambda.zip .
      
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
        cd ./terraform
        terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: |
        cd ./terraform
        terraform apply -auto-approve -var-file="terraform.tfvars" \
          --var top_domain=${{ var.AWS_DOMAIN }} \
          --var subdomain=${{ var.AWS_SUBDOMAIN }} \
          --var region=${{ var.AWS_REGION }} \
          --var cert_arn=${{ var.AWS_CERT_ARN }} \
          --var db_name =${{ var.AWS_DB_NAME }} \
          --var db_username =${{ var.AWS_DB_USER }} \

