name: Install Dependencies
description: Install common dependencies for a project
inputs:
  python-version:
    description: Python version to use
    default: "3.10"
  app-directory:
    description: The app directory (where you keep your requirements.txt files)
    default: ./app
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Python Virtual Environment
      shell: bash
      run: cd ${{ inputs.app-directory}} && python3 -m pip install --upgrade pip && pip3 install  --no-input -r requirements.txt && cd .. && python setup.py develop