name: Install Dependencies
description: Install common dependencies for a project
inputs:
  python-version:
    description: Python version to use
    default: "3.10"
  requirements-path:
    description: Path to the requirements file
    required: true
    default: "app/requirements.txt"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python Virtual Environment
      shell: bash
      run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r app/requirements.txt && python setup.py develop