name: Install Dependencies
description: Install common dependencies for a project
inputs:
  python-version:
    description: Python version to use
    default: "3.10"
  requirements-path:
    description: Path to the requirements file
    required: true
    default: "app/requirements.txt"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ inputs.requirements-path }}