# name: api-tests
# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   api-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Run API Tests
#         uses: ./.github/actions/api-tests
#         with:
#           base-url: ${{ inputs.base-url }}
#           env-vars: ${{ inputs.env-vars }}

#       - name: Wait until API responds
#         run: timeout 1m bash -c "until curl -s '${{ inputs.base-url }}/status?debug=true'; do sleep 5 ; done"

#       - name: Wait until API connects to the DB
#         run: timeout 2m bash -c "until curl -s ${{ inputs.base-url }}/status | python3 -c \"import sys, json; json.load(sys.stdin)['db']['hasRequiredTableAccess'] or sys.exit(1)\"; do sleep 5 ; done"
