name: run-tests
on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    timeout-minutes: 3
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/common/install-dependencies

      - name: Produce seed data
        run:  ./database-seed/generate.sh

      - name: Setup database
        run: docker compose up -d database

      - name: Wait until DB is accepting connections
        run: timeout 2m bash -c "until docker compose logs --tail 10 | grep 'underground' | grep 'database system is ready to accept connections'; do sleep 5 ; done"

      - name: Run Tests
        run: pytest